2 - Napravi REST servis koji omogucava dodavanje bicikla
BozoKvesic/bicycle-project pull request #3
Opened 2022-07-01 09:48 UTC by BozoKvesic

2022-07-01 09:51 UTC, jsolja commented
Za ubucude: commit message takoder mora imati svoj format. Generalno dobra praksa je da pises ovakav message:
<identifikator ticketa> - <precizno objasnjenje sto si promjenio/dodao>

Primjer:
2 - Created BikeController, BikeRepository and LoadDatabase to fetch bikes from database.

2022-07-01 09:54 UTC, jsolja commented on src/main/java/com/spring/boot/kickstart/bicycleproject/LoadDatabase.java
> +
Nije frka, ali odrzavaj kod urednim pa obrisi ovaj empty line. Empty line se ponekad koristi za razdvajanje malih "otoka" logike unutar metode. Npr: prvih 4 linija je deklaracija, pa empty line, pa nekakva business logika, pa empty line, pa return statement di vracas izracunatu vrijednost.

2022-07-01 10:02 UTC, jsolja commented on src/main/java/com/spring/boot/kickstart/bicycleproject/controller/BikeController.java
> +        return this.repository.save(newBike);
Nije dobro pozivati najnizi sloj iz najviseg sloja aplikacije. Bitno je stvoriti slojevitu arhitekturu, iako je ovo jedna linija koda. Tako da kreiraj ovakav koncept:
Controller poziva fasadu, fasada poziva servis, servis poziva repozitorij koji radi s bazom podataka. 
Kreiraj BikeFacade, BikeService klase. BikeController ce pozivati BikeFacade, BikeFacade ce pozivati BikeService, BikeService ce pozivati BikeRepository.

2022-07-01 10:06 UTC, jsolja commented on src/main/java/com/spring/boot/kickstart/bicycleproject/exception/BikeNotFoundException.java
> +        super("Could not find bike " + id);
"Could not find bike by ID: " + id

2022-07-01 10:07 UTC, jsolja commented on src/main/java/com/spring/boot/kickstart/bicycleproject/repository/BikeRepository.java
> +    Optional<List<Bike>> findAllByBrand(String brand);
Zasto findAllByBrand a ne findAllByCode?

2022-07-01 10:08 UTC, jsolja commented on src/main/java/com/spring/boot/kickstart/bicycleproject/repository/BikeRepository.java
> +    Optional<List<Bike>> findAllByBrand(String brand);
Uostalom, gdje se ovo koristi za sad? S obzirom da je za sad jedini zahtjev kreiranje bicikla.

2022-07-01 10:09 UTC, jsolja requested changes
Vidi komentare na PRu.

2022-07-01 12:55 UTC, jsolja commented on src/main/java/com/spring/boot/kickstart/bicycleproject/facade/BikeFacade.java
> +    Bike newBike(Bike bike);
Nazovi metodu "createNewBike", obicno je praksa da naziv metode bude u imperativu.

2022-07-01 12:57 UTC, jsolja commented on src/main/java/com/spring/boot/kickstart/bicycleproject/facade/BikeFacade.java
> +    Bike newBike(Bike bike);
Istu promjenu napravi i u kontroleru i servisu.

2022-07-01 13:00 UTC, jsolja commented on src/main/java/com/spring/boot/kickstart/bicycleproject/facade/impl/BikeFacadeImpl.java
> +@Service
Nisam siguran da li je ovo najbolja anotacija za Facade klasu. Ovo slobodno istrazis, provjeri da li se Facade gleda kao klasa na servisnoj razini ili medu-razina izmedu prezentacijskog i servisnog sloja. Mozda je bolje da stavis @Component, ali dajem ti slobodu da ti odlucis :)

2022-07-01 13:07 UTC, BozoKvesic commented on src/main/java/com/spring/boot/kickstart/bicycleproject/facade/impl/BikeFacadeImpl.java
> +@Service
Facade: Delegates client requests to appropriate subsystem classes.
Mozda ipak ima vise smisla @Component jer se servisi nalaze u tom subsystemu

2022-07-04 06:08 UTC, jsolja approved these changes

2022-07-04 06:08 UTC, merged